
namespace WEditor
{
    partial class AnimList
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.listBox1 = new System.Windows.Forms.ListBox();
            this.btnSaveCurrent = new System.Windows.Forms.Button();
            this.cbxSelectedAnimFile = new System.Windows.Forms.ComboBox();
            this.SuspendLayout();
            // 
            // listBox1
            // 
            this.listBox1.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.listBox1.FormattingEnabled = true;
            this.listBox1.Items.AddRange(new object[] {
            "0x0 Secret Power",
            "0x1f Pound,Dig2,ExtremeSpeed,Endeavor",
            "0x20 Karate Chop",
            "0x21 DoubleSlap",
            "0x22 Comet Punch,Strength",
            "0x23 Mega Punch",
            "0x24 Pay Day",
            "0x25 FirePunch",
            "0x26 IcePunch",
            "0x27 ThunderPunch",
            "0x28 Scratch",
            "0x29 ViceGrip",
            "0x2a Guillotine",
            "0x2b Razor Wind",
            "0x2c Swords Dance",
            "0x2d Cut",
            "0x2e Gust",
            "0x2f Wing Attack",
            "0x30 Whirlwind",
            "0x31 Fly",
            "0x32 Bind",
            "0x33 Slam",
            "0x34 Vine Whip",
            "0x35 Stomp",
            "0x36 Double Kick",
            "0x37 Mega Kick",
            "0x38 Jump Kick",
            "0x39 Rolling Kick",
            "0x3a Sand-Attack",
            "0x3b Headbutt",
            "0x3c Horn Attack",
            "0x3d Fury Attack",
            "0x3e Horn Drill",
            "0x3f Tackle",
            "0x40 Body Slam",
            "0x41 Wrap",
            "0x42 Take Down",
            "0x43 Thrash",
            "0x44 Double-Edge",
            "0x45",
            "0x46 Poison Sting",
            "0x47 Twineedle",
            "0x48 Pin Missile",
            "0x49 Leer",
            "0x4a Bite",
            "0x4b Growl",
            "0x4c Roar",
            "0x4d Sing",
            "0x4e Supersonic",
            "0x4f SonicBoom",
            "0x50 Disable",
            "0x51 Acid",
            "0x52 Ember",
            "0x53 Flamethrower,Blast Burn2",
            "0x54 Mist",
            "0x55 Water Gun",
            "0x56 Hydro Pump",
            "0x57",
            "0x58 Ice Beam",
            "0x59 Blizzard",
            "0x5a Psybeam",
            "0x5b BubbleBeam",
            "0x5c Aurora Beam",
            "0x5d Hyper Beam",
            "0x5e Peck,Drill Peck",
            "0x5f",
            "0x60 Submission",
            "0x61 Low Kick",
            "0x62 Counter",
            "0x63 Seismic Toss",
            "0x64",
            "0x65 Absorb",
            "0x66 Mega Drain",
            "0x67 Leech Seed",
            "0x68 NOT Growth",
            "0x69 Razor Leaf",
            "0x6a SolarBeam",
            "0x6b PoisonPowder",
            "0x6c Stun Spore",
            "0x6d Sleep Powder",
            "0x6e Petal Dance",
            "0x6f String Shot",
            "0x70 Dtagon Rage",
            "0x71 Fire Spin",
            "0x72 ThunderShock",
            "0x73 Thunderbolt",
            "0x74 Thunder Wave",
            "0x75 Thunder",
            "0x76 Rock Throw",
            "0x77 Earthquake",
            "0x78 Fissure",
            "0x79 Dig",
            "0x7a Toxic",
            "0x7b NOT Confusion",
            "0x7c NOT Psychic",
            "0x7d Hypnosis",
            "0x7e Agility",
            "0x7f Quick Attack",
            "0x80 Rage",
            "0x81 Teleport",
            "Night Shade : ?",
            "0x82 Mimic",
            "0x83 Screech",
            "Double Team : ?",
            "0x84 Recover",
            "0x85 Harden",
            "Minumize : ?",
            "0x86 SmokeScreen",
            "0x87 Confuse Ray",
            "0x88 Withdraw",
            "0x89 Defence Curl",
            "0x8a Barrier",
            "0x8b Light Screen",
            "0x8c Haze",
            "0x8d Reflect",
            "0x8e Focus Energy",
            "0x8f Bide",
            "Metronome : ?",
            "Mirror MOve : ? : Only 04 00 00 00",
            "0x90 Selfdestruct",
            "0x91 Egg Bomb",
            "0x92 Lick",
            "0x93 Smog",
            "0x94 Sludge",
            "0x95 Bone Club",
            "0x96 Fire Blast",
            "0x97 Waterfall",
            "0x98 Clamp",
            "0x99 Swift",
            "0x9a Skull Bash",
            "0x9b Spike Cannon",
            "0x9c NOT Constrict : ?",
            "0x9d Amnesia",
            "Kinesis : ?",
            "0x9e Softboiled",
            "0x9f Hi Jump Kick",
            "Glare : ?",
            "0xa0",
            "0xa1",
            "0xa2 Poison Gas",
            "0xa3 Barrage",
            "0xa4 Leech Life",
            "0xa5 Lovely Kiss",
            "0xa6 Sky Attack",
            "Transform : ?",
            "0xa7 BubbleBeam",
            "0xa8 Dizzy Punch",
            "0xa9 Spore",
            "Flash : ?",
            "0xaa Psywave",
            "0xab Splash",
            "0xac Acid Armor",
            "0xad Crabhammer",
            "0xae Explosion",
            "0xaf Fury Swipes",
            "\t0x10-0x1e Unused",
            "0x1f Bonemerang",
            "\t0x20-0xaf Unused",
            "0xb0 Rest",
            "0xb1 Rock Slide",
            "0xb2 Hyper Fang",
            "0xb3 Sharpen",
            "0xb4 Conversion",
            "0xb5 Tri Attack",
            "0xb6 Super Fung",
            "0xb7 Slash",
            "0xb8 Substitute : ?",
            "0xb9 Struggle",
            "0xba Sketch,-",
            "0xbb Triple Kick",
            "0xbc Thief",
            "0xbd Spider Web",
            "0xbe Mind Reader",
            "Nightmare : ?",
            "0xbf Flame Wheel",
            "0xc0 Snore",
            "0xc1 Curse",
            "0xc2 Flail",
            "0xc3 Conversion",
            "0xc4 Aeroblast",
            "0xc5 Cotton Spore",
            "0xc6 Reversal",
            "0xc7 Spite : ?",
            "0xc8 Powder Snow",
            "0xc9 Protect",
            "0xca Mach Punch",
            "0xcb Scary Face : ? ",
            "0xcc Faint Attack",
            "0xcd Sweet Kiss",
            "0xce Belly Drum",
            "0xcf Sludge Bomb",
            "0xd0 Mud-Slap",
            "0xd1 Octazooka",
            "0xd2 Spikes",
            "0xd3 Zap Cannon",
            "0xd4 Foresight : ? ",
            "0xd5 Destiny Bond",
            "0xd6 Perish Song",
            "0xd7 Icy Wind",
            "0xd8 Detect,Tickle",
            "0xd9 Bone Rush",
            "Lock-On : ?",
            "0xda Outrage",
            "0xdb Sandstotm",
            "0xdc Giga Drain",
            "0xdd Endure",
            "0xde Charm",
            "0xdf Rollout",
            "0xe0 False Swipe",
            "0xe1 Swagger : ?",
            "0xe2 Milk Drink",
            "0xe3 Spark",
            "0xe4 Fury Cutter",
            "0xe5 Steel Wing",
            "Mean Look : ?",
            "0xe6 Attract",
            "0xe7 Sleep Talk",
            "0xe8 Heal Bell",
            "0xe9 Return",
            "0xea Present",
            "0xeb Frustration",
            "0xec Safeguard",
            "0xed Pain Split",
            "0xee Sacred Fire",
            "0xef Magnitude : ?",
            "0xf0 DynamicPunch",
            "0xf1 Megahorn",
            "0xf2 DragonBreath",
            "0xf3 Baton Pass",
            "0xf4 Encore",
            "0xf5 Pursuit",
            "0xf6 Rapid Spin",
            "0xf7 Sweet Scent",
            "0xf8 Iron Tail",
            "0xf9 Metal Claw : ?",
            "0xfa Vital Throw",
            "0xfb Morning Sun",
            "0xfc Synthesis",
            "0xfd Moonlight",
            "0xfe Hidden Power",
            "0xff Cross Chop",
            "0x100 Twister",
            "0x101 Rain Dance",
            "0x102 Sunny Day",
            "0x103 Crunch",
            "0x104 Mirror Coat",
            "0x105 Psych Up",
            "0x106",
            "0x107 Ancient Power",
            "0x108 Shadow Ball",
            "0x109 Future Sight : ?",
            "0x10a Rock Smash",
            "0x10b Whirlpool",
            "0x10c Beat Up",
            "0x10d Fake Out",
            "0x10e Uproar",
            "0x10f Stockpile",
            "0x110 Spit Up",
            "0x111 Swallow",
            "0x112 Heat Wave",
            "0x113 Hail",
            "0x114 Torment : ?",
            "0x115 Flatter",
            "0x116 Will-O-Wisp",
            "0x117 Memento : ?",
            "0x118 Facade",
            "0x119 Focus Punch",
            "0x11a SmellingSalt",
            "0x11b FollowMe : ?",
            "0x11c Nature Power : ? : Only 04 00 00 00",
            "0x11d Charge",
            "0x11e Taunt",
            "0x11f Helping Hand : ?",
            "0x120 Trick : ?",
            "0x121 Role Play : ?",
            "0x122 Wish",
            "0x123 Assist : ?",
            "0x124 Ingrain",
            "0x125 Superpower",
            "0x126 Magic Coat",
            "0x127 Recycle",
            "0x128 Revenge",
            "0x129 Brick Break",
            "0x12a Yawn",
            "0x12b Knock Off",
            "0x12c",
            "0x12d Eruption",
            "0x12e Skill Swap",
            "0x12f Imprison,Block",
            "0x130 Rehresh",
            "0x131 Grudge : ?",
            "0x132 Snatch : ?",
            "0x133",
            "0x134 Dive",
            "0x135 Arm Thrust",
            "0x136 Camouflage : ?",
            "0x137 Tail Glow",
            "0x138 Luster Purge",
            "0x139 Mist Ball",
            "0x13a FeatherDance",
            "0x13b Teeter Dance",
            "0x13c Blaze Kick",
            "0x13d Mud Sport",
            "0x13e Ice Ball",
            "0x13f Needle Arm",
            "0x140 Slack Off",
            "0x141 Hyper Voice",
            "0x142 Poison Fang",
            "Crush Claw : ?",
            "0x144 Blast Burn",
            "0x145 Hydro Cannon",
            "0x146 Meteor Mash",
            "0x147 Astonish",
            "0x148 Weather Ball",
            "0x149 Atomatherapy",
            "0x14a Fake Tears",
            "0x14b Air Cutter",
            "0x14c Overheat",
            "0x14d Odor Sleuth : ?",
            "0x14e Rock Tomb",
            "0x14f Silver Wind",
            "0x150 Metal Sound",
            "0x151 GrassWhistle",
            "0x152",
            "0x153 Cosmic Power",
            "0x154 Water Spout",
            "0x155 Signal Beam",
            "0x156 Shadow Punch",
            "0x157 Extrasensory",
            "0x158 Sky Uppercut",
            "0x159 Sand Tomb",
            "0x15a Sheer Cold",
            "0x15b Muddy Water",
            "0x15c Bullet Seed",
            "0x15d Aerial Ace",
            "0x15e Icicle Spear",
            "0x15f Iron Defence : ?",
            "0x160",
            "0x161 Howl",
            "0x162 Dragon Claw",
            "0x163 Frenzy Plant",
            "0x164 Bulk Up : ?",
            "0x165 Bounce,Fly2",
            "0x166 Mud Shot",
            "0x167 Poison Tail",
            "0x168 Covet",
            "0x169 Volt Tackle",
            "0x16a Magical Leaf",
            "0x16b Water Sport",
            "0x16c Calm Mind",
            "0x16d Leaf Blade",
            "0x16e Dragon Dance",
            "0x16f Rock Blast",
            "0x170 Shock Wave",
            "0x171 Water Pulse",
            "0x172 Doom Desire",
            "0x173 Psycho Boost",
            "0x174 Roost",
            "0x175 Gravity",
            "0x176 Miracle Eye",
            "0x177 Wake-Up Slap",
            "0x178 Hammer Arm",
            "0x179 Gyro Ball",
            "0x17a Healing Wish",
            "0x17b Brine",
            "0x17c Natural Gift",
            "0x17d Feint",
            "0x17e Pluck",
            "0x17f Tailwind",
            "0x180 Acupressure",
            "0x181 Metal Burst",
            "0x182 U-turn",
            "0x183 Close Combat",
            "0x184 Patback",
            "0x185 Assurance",
            "0x186 Embargo",
            "0x187 Fling",
            "0x188 Psycho Shift",
            "0x189 Trump Card",
            "0x18a Heal Block",
            "0x18b Wring Out",
            "0x18c Power Trick",
            "0x18d Gastro Acid",
            "0x18e Lucky Chant",
            "0x18f Me First",
            "0x190 Copycat",
            "0x191 Power Swap",
            "0x192 Guard Swap",
            "0x193 Punishment",
            "0x194 Last Resort",
            "0x195 Worry Seed",
            "0x196 Sucker Punch",
            "0x197 Toxic Spikes",
            "0x198 Heart Swap",
            "0x199 Aqua Ring",
            "0x19a Magnet Rise",
            "0x19b Flare Blitz",
            "0x19c Force Palm",
            "0x19d Aura Sphere",
            "0x19e Rock Polish",
            "0x19f Poison Jab",
            "0x1a0 Dark Pulse",
            "0x1a1 Night Slash",
            "0x1a2 Aqua Tail",
            "0x1a3 Seed Bomb",
            "0x1a4 Air Slash",
            "0x1a5 X-Scissor",
            "0x1a6 Bug Buzz",
            "0x1a7 Dragon Pulse",
            "0x1a8 Dragon Rush",
            "0x1a9 Power Gem",
            "0x1aa Drain Punch,Dream Eater",
            "0x1ab Vacuum Wave",
            "0x1ac Focus Blast",
            "0x1ad Energy Ball",
            "0x1ae Brave Bird",
            "0x1af Earth Power",
            "0x1b0 Switcheroo : ?",
            "0x1b1 Giga Impact",
            "0x1b2 Nasty Plot",
            "0x1b3 Bullet Punch",
            "0x1b4 Avalanche",
            "0x1b5 Ice Shard",
            "0x1b6 Shadow Claw",
            "0x1b7 Thunder Fang",
            "0x1b8 Ice Fang",
            "0x1b9 Fire Fang",
            "0x1ba Shadow Sneak",
            "0x1bb Mud Bomb",
            "0x1bc Psycho Cut",
            "0x1bd Zen Headbutt",
            "0x1be Mirrir Shot",
            "0x1bf Flash Cannon",
            "0x1c0 Rock Climb",
            "0x1c1 Defog",
            "0x1c2 Trick Room : ?",
            "0x1c3 Draco Meteor",
            "0x1c4 Dischage",
            "0x1c5 Lava Plume",
            "0x1c6 Leaf Storm",
            "0x1c7 Power Whip",
            "0x1c8 Rock Wrecker",
            "0x1c9 Cross Poison",
            "0x1ca Gunk Shot",
            "0x1cb Iron Head",
            "0x1cc Megnet Bomb",
            "0x1cd Stone Edge",
            "0x1ce Captivate",
            "0x1cf Stealth Rock",
            "0x1d0 Grass Knot",
            "0x1d1 Chatter",
            "0x1d2 Judgment",
            "0x1d3 Bug Bite",
            "0x1d4 Charge Beam",
            "0x1d5 Wood Hammer",
            "0x1d6 Aqua Jet,Surf",
            "0x1d7 Attack Order",
            "0x1d8 Defend Order",
            "0x1d9 Heal Order",
            "0x1da Head Smash",
            "0x1db Double Hit",
            "0x1dc Roar if Time",
            "0x1dd Special Rend",
            "0x1de Lunar Dance",
            "0x1df Crush Grip",
            "0x1e0 Magma Storm",
            "0x1e1 Dark Void",
            "0x1e2 Seed Flare",
            "0x1e3 Ominous Wind",
            "0x1e4 Shadow Force"});
            this.listBox1.Location = new System.Drawing.Point(9, 36);
            this.listBox1.Margin = new System.Windows.Forms.Padding(2, 3, 2, 3);
            this.listBox1.Name = "listBox1";
            this.listBox1.Size = new System.Drawing.Size(236, 316);
            this.listBox1.TabIndex = 0;
            this.listBox1.SelectedIndexChanged += new System.EventHandler(this.listBox1_SelectedIndexChanged);
            // 
            // btnSaveCurrent
            // 
            this.btnSaveCurrent.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.btnSaveCurrent.Location = new System.Drawing.Point(138, 369);
            this.btnSaveCurrent.Margin = new System.Windows.Forms.Padding(2, 3, 2, 3);
            this.btnSaveCurrent.Name = "btnSaveCurrent";
            this.btnSaveCurrent.Size = new System.Drawing.Size(106, 20);
            this.btnSaveCurrent.TabIndex = 2;
            this.btnSaveCurrent.Text = "Close";
            this.btnSaveCurrent.UseVisualStyleBackColor = true;
            this.btnSaveCurrent.Click += new System.EventHandler(this.btnSaveCurrent_Click);
            // 
            // cbxSelectedAnimFile
            // 
            this.cbxSelectedAnimFile.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.cbxSelectedAnimFile.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.Suggest;
            this.cbxSelectedAnimFile.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.ListItems;
            this.cbxSelectedAnimFile.FormattingEnabled = true;
            this.cbxSelectedAnimFile.Items.AddRange(new object[] {
            "0x0 Secret Power",
            "0x1f Pound,Dig2,ExtremeSpeed,Endeavor",
            "0x20 Karate Chop",
            "0x21 DoubleSlap",
            "0x22 Comet Punch,Strength",
            "0x23 Mega Punch",
            "0x24 Pay Day",
            "0x25 FirePunch",
            "0x26 IcePunch",
            "0x27 ThunderPunch",
            "0x28 Scratch",
            "0x29 ViceGrip",
            "0x2a Guillotine",
            "0x2b Razor Wind",
            "0x2c Swords Dance",
            "0x2d Cut",
            "0x2e Gust",
            "0x2f Wing Attack",
            "0x30 Whirlwind",
            "0x31 Fly",
            "0x32 Bind",
            "0x33 Slam",
            "0x34 Vine Whip",
            "0x35 Stomp",
            "0x36 Double Kick",
            "0x37 Mega Kick",
            "0x38 Jump Kick",
            "0x39 Rolling Kick",
            "0x3a Sand-Attack",
            "0x3b Headbutt",
            "0x3c Horn Attack",
            "0x3d Fury Attack",
            "0x3e Horn Drill",
            "0x3f Tackle",
            "0x40 Body Slam",
            "0x41 Wrap",
            "0x42 Take Down",
            "0x43 Thrash",
            "0x44 Double-Edge",
            "0x45",
            "0x46 Poison Sting",
            "0x47 Twineedle",
            "0x48 Pin Missile",
            "0x49 Leer",
            "0x4a Bite",
            "0x4b Growl",
            "0x4c Roar",
            "0x4d Sing",
            "0x4e Supersonic",
            "0x4f SonicBoom",
            "0x50 Disable",
            "0x51 Acid",
            "0x52 Ember",
            "0x53 Flamethrower,Blast Burn2",
            "0x54 Mist",
            "0x55 Water Gun",
            "0x56 Hydro Pump",
            "0x57",
            "0x58 Ice Beam",
            "0x59 Blizzard",
            "0x5a Psybeam",
            "0x5b BubbleBeam",
            "0x5c Aurora Beam",
            "0x5d Hyper Beam",
            "0x5e Peck,Drill Peck",
            "0x5f",
            "0x60 Submission",
            "0x61 Low Kick",
            "0x62 Counter",
            "0x63 Seismic Toss",
            "0x64",
            "0x65 Absorb",
            "0x66 Mega Drain",
            "0x67 Leech Seed",
            "0x68 NOT Growth",
            "0x69 Razor Leaf",
            "0x6a SolarBeam",
            "0x6b PoisonPowder",
            "0x6c Stun Spore",
            "0x6d Sleep Powder",
            "0x6e Petal Dance",
            "0x6f String Shot",
            "0x70 Dtagon Rage",
            "0x71 Fire Spin",
            "0x72 ThunderShock",
            "0x73 Thunderbolt",
            "0x74 Thunder Wave",
            "0x75 Thunder",
            "0x76 Rock Throw",
            "0x77 Earthquake",
            "0x78 Fissure",
            "0x79 Dig",
            "0x7a Toxic",
            "0x7b NOT Confusion",
            "0x7c NOT Psychic",
            "0x7d Hypnosis",
            "0x7e Agility",
            "0x7f Quick Attack",
            "0x80 Rage",
            "0x81 Teleport",
            "Night Shade : ?",
            "0x82 Mimic",
            "0x83 Screech",
            "Double Team : ?",
            "0x84 Recover",
            "0x85 Harden",
            "Minumize : ?",
            "0x86 SmokeScreen",
            "0x87 Confuse Ray",
            "0x88 Withdraw",
            "0x89 Defence Curl",
            "0x8a Barrier",
            "0x8b Light Screen",
            "0x8c Haze",
            "0x8d Reflect",
            "0x8e Focus Energy",
            "0x8f Bide",
            "Metronome : ?",
            "Mirror MOve : ? : Only 04 00 00 00",
            "0x90 Selfdestruct",
            "0x91 Egg Bomb",
            "0x92 Lick",
            "0x93 Smog",
            "0x94 Sludge",
            "0x95 Bone Club",
            "0x96 Fire Blast",
            "0x97 Waterfall",
            "0x98 Clamp",
            "0x99 Swift",
            "0x9a Skull Bash",
            "0x9b Spike Cannon",
            "0x9c NOT Constrict : ?",
            "0x9d Amnesia",
            "Kinesis : ?",
            "0x9e Softboiled",
            "0x9f Hi Jump Kick",
            "Glare : ?",
            "0xa0",
            "0xa1",
            "0xa2 Poison Gas",
            "0xa3 Barrage",
            "0xa4 Leech Life",
            "0xa5 Lovely Kiss",
            "0xa6 Sky Attack",
            "Transform : ?",
            "0xa7 BubbleBeam",
            "0xa8 Dizzy Punch",
            "0xa9 Spore",
            "Flash : ?",
            "0xaa Psywave",
            "0xab Splash",
            "0xac Acid Armor",
            "0xad Crabhammer",
            "0xae Explosion",
            "0xaf Fury Swipes",
            "\t0x10-0x1e Unused",
            "0x1f Bonemerang",
            "\t0x20-0xaf Unused",
            "0xb0 Rest",
            "0xb1 Rock Slide",
            "0xb2 Hyper Fang",
            "0xb3 Sharpen",
            "0xb4 Conversion",
            "0xb5 Tri Attack",
            "0xb6 Super Fung",
            "0xb7 Slash",
            "0xb8 Substitute : ?",
            "0xb9 Struggle",
            "0xba Sketch,-",
            "0xbb Triple Kick",
            "0xbc Thief",
            "0xbd Spider Web",
            "0xbe Mind Reader",
            "Nightmare : ?",
            "0xbf Flame Wheel",
            "0xc0 Snore",
            "0xc1 Curse",
            "0xc2 Flail",
            "0xc3 Conversion",
            "0xc4 Aeroblast",
            "0xc5 Cotton Spore",
            "0xc6 Reversal",
            "0xc7 Spite : ?",
            "0xc8 Powder Snow",
            "0xc9 Protect",
            "0xca Mach Punch",
            "0xcb Scary Face : ? ",
            "0xcc Faint Attack",
            "0xcd Sweet Kiss",
            "0xce Belly Drum",
            "0xcf Sludge Bomb",
            "0xd0 Mud-Slap",
            "0xd1 Octazooka",
            "0xd2 Spikes",
            "0xd3 Zap Cannon",
            "0xd4 Foresight : ? ",
            "0xd5 Destiny Bond",
            "0xd6 Perish Song",
            "0xd7 Icy Wind",
            "0xd8 Detect,Tickle",
            "0xd9 Bone Rush",
            "Lock-On : ?",
            "0xda Outrage",
            "0xdb Sandstotm",
            "0xdc Giga Drain",
            "0xdd Endure",
            "0xde Charm",
            "0xdf Rollout",
            "0xe0 False Swipe",
            "0xe1 Swagger : ?",
            "0xe2 Milk Drink",
            "0xe3 Spark",
            "0xe4 Fury Cutter",
            "0xe5 Steel Wing",
            "Mean Look : ?",
            "0xe6 Attract",
            "0xe7 Sleep Talk",
            "0xe8 Heal Bell",
            "0xe9 Return",
            "0xea Present",
            "0xeb Frustration",
            "0xec Safeguard",
            "0xed Pain Split",
            "0xee Sacred Fire",
            "0xef Magnitude : ?",
            "0xf0 DynamicPunch",
            "0xf1 Megahorn",
            "0xf2 DragonBreath",
            "0xf3 Baton Pass",
            "0xf4 Encore",
            "0xf5 Pursuit",
            "0xf6 Rapid Spin",
            "0xf7 Sweet Scent",
            "0xf8 Iron Tail",
            "0xf9 Metal Claw : ?",
            "0xfa Vital Throw",
            "0xfb Morning Sun",
            "0xfc Synthesis",
            "0xfd Moonlight",
            "0xfe Hidden Power",
            "0xff Cross Chop",
            "0x100 Twister",
            "0x101 Rain Dance",
            "0x102 Sunny Day",
            "0x103 Crunch",
            "0x104 Mirror Coat",
            "0x105 Psych Up",
            "0x106",
            "0x107 Ancient Power",
            "0x108 Shadow Ball",
            "0x109 Future Sight : ?",
            "0x10a Rock Smash",
            "0x10b Whirlpool",
            "0x10c Beat Up",
            "0x10d Fake Out",
            "0x10e Uproar",
            "0x10f Stockpile",
            "0x110 Spit Up",
            "0x111 Swallow",
            "0x112 Heat Wave",
            "0x113 Hail",
            "0x114 Torment : ?",
            "0x115 Flatter",
            "0x116 Will-O-Wisp",
            "0x117 Memento : ?",
            "0x118 Facade",
            "0x119 Focus Punch",
            "0x11a SmellingSalt",
            "0x11b FollowMe : ?",
            "0x11c Nature Power : ? : Only 04 00 00 00",
            "0x11d Charge",
            "0x11e Taunt",
            "0x11f Helping Hand : ?",
            "0x120 Trick : ?",
            "0x121 Role Play : ?",
            "0x122 Wish",
            "0x123 Assist : ?",
            "0x124 Ingrain",
            "0x125 Superpower",
            "0x126 Magic Coat",
            "0x127 Recycle",
            "0x128 Revenge",
            "0x129 Brick Break",
            "0x12a Yawn",
            "0x12b Knock Off",
            "0x12c",
            "0x12d Eruption",
            "0x12e Skill Swap",
            "0x12f Imprison,Block",
            "0x130 Rehresh",
            "0x131 Grudge : ?",
            "0x132 Snatch : ?",
            "0x133",
            "0x134 Dive",
            "0x135 Arm Thrust",
            "0x136 Camouflage : ?",
            "0x137 Tail Glow",
            "0x138 Luster Purge",
            "0x139 Mist Ball",
            "0x13a FeatherDance",
            "0x13b Teeter Dance",
            "0x13c Blaze Kick",
            "0x13d Mud Sport",
            "0x13e Ice Ball",
            "0x13f Needle Arm",
            "0x140 Slack Off",
            "0x141 Hyper Voice",
            "0x142 Poison Fang",
            "Crush Claw : ?",
            "0x144 Blast Burn",
            "0x145 Hydro Cannon",
            "0x146 Meteor Mash",
            "0x147 Astonish",
            "0x148 Weather Ball",
            "0x149 Atomatherapy",
            "0x14a Fake Tears",
            "0x14b Air Cutter",
            "0x14c Overheat",
            "0x14d Odor Sleuth : ?",
            "0x14e Rock Tomb",
            "0x14f Silver Wind",
            "0x150 Metal Sound",
            "0x151 GrassWhistle",
            "0x152",
            "0x153 Cosmic Power",
            "0x154 Water Spout",
            "0x155 Signal Beam",
            "0x156 Shadow Punch",
            "0x157 Extrasensory",
            "0x158 Sky Uppercut",
            "0x159 Sand Tomb",
            "0x15a Sheer Cold",
            "0x15b Muddy Water",
            "0x15c Bullet Seed",
            "0x15d Aerial Ace",
            "0x15e Icicle Spear",
            "0x15f Iron Defence : ?",
            "0x160",
            "0x161 Howl",
            "0x162 Dragon Claw",
            "0x163 Frenzy Plant",
            "0x164 Bulk Up : ?",
            "0x165 Bounce,Fly2",
            "0x166 Mud Shot",
            "0x167 Poison Tail",
            "0x168 Covet",
            "0x169 Volt Tackle",
            "0x16a Magical Leaf",
            "0x16b Water Sport",
            "0x16c Calm Mind",
            "0x16d Leaf Blade",
            "0x16e Dragon Dance",
            "0x16f Rock Blast",
            "0x170 Shock Wave",
            "0x171 Water Pulse",
            "0x172 Doom Desire",
            "0x173 Psycho Boost",
            "0x174 Roost",
            "0x175 Gravity",
            "0x176 Miracle Eye",
            "0x177 Wake-Up Slap",
            "0x178 Hammer Arm",
            "0x179 Gyro Ball",
            "0x17a Healing Wish",
            "0x17b Brine",
            "0x17c Natural Gift",
            "0x17d Feint",
            "0x17e Pluck",
            "0x17f Tailwind",
            "0x180 Acupressure",
            "0x181 Metal Burst",
            "0x182 U-turn",
            "0x183 Close Combat",
            "0x184 Patback",
            "0x185 Assurance",
            "0x186 Embargo",
            "0x187 Fling",
            "0x188 Psycho Shift",
            "0x189 Trump Card",
            "0x18a Heal Block",
            "0x18b Wring Out",
            "0x18c Power Trick",
            "0x18d Gastro Acid",
            "0x18e Lucky Chant",
            "0x18f Me First",
            "0x190 Copycat",
            "0x191 Power Swap",
            "0x192 Guard Swap",
            "0x193 Punishment",
            "0x194 Last Resort",
            "0x195 Worry Seed",
            "0x196 Sucker Punch",
            "0x197 Toxic Spikes",
            "0x198 Heart Swap",
            "0x199 Aqua Ring",
            "0x19a Magnet Rise",
            "0x19b Flare Blitz",
            "0x19c Force Palm",
            "0x19d Aura Sphere",
            "0x19e Rock Polish",
            "0x19f Poison Jab",
            "0x1a0 Dark Pulse",
            "0x1a1 Night Slash",
            "0x1a2 Aqua Tail",
            "0x1a3 Seed Bomb",
            "0x1a4 Air Slash",
            "0x1a5 X-Scissor",
            "0x1a6 Bug Buzz",
            "0x1a7 Dragon Pulse",
            "0x1a8 Dragon Rush",
            "0x1a9 Power Gem",
            "0x1aa Drain Punch,Dream Eater",
            "0x1ab Vacuum Wave",
            "0x1ac Focus Blast",
            "0x1ad Energy Ball",
            "0x1ae Brave Bird",
            "0x1af Earth Power",
            "0x1b0 Switcheroo : ?",
            "0x1b1 Giga Impact",
            "0x1b2 Nasty Plot",
            "0x1b3 Bullet Punch",
            "0x1b4 Avalanche",
            "0x1b5 Ice Shard",
            "0x1b6 Shadow Claw",
            "0x1b7 Thunder Fang",
            "0x1b8 Ice Fang",
            "0x1b9 Fire Fang",
            "0x1ba Shadow Sneak",
            "0x1bb Mud Bomb",
            "0x1bc Psycho Cut",
            "0x1bd Zen Headbutt",
            "0x1be Mirrir Shot",
            "0x1bf Flash Cannon",
            "0x1c0 Rock Climb",
            "0x1c1 Defog",
            "0x1c2 Trick Room : ?",
            "0x1c3 Draco Meteor",
            "0x1c4 Dischage",
            "0x1c5 Lava Plume",
            "0x1c6 Leaf Storm",
            "0x1c7 Power Whip",
            "0x1c8 Rock Wrecker",
            "0x1c9 Cross Poison",
            "0x1ca Gunk Shot",
            "0x1cb Iron Head",
            "0x1cc Megnet Bomb",
            "0x1cd Stone Edge",
            "0x1ce Captivate",
            "0x1cf Stealth Rock",
            "0x1d0 Grass Knot",
            "0x1d1 Chatter",
            "0x1d2 Judgment",
            "0x1d3 Bug Bite",
            "0x1d4 Charge Beam",
            "0x1d5 Wood Hammer",
            "0x1d6 Aqua Jet,Surf",
            "0x1d7 Attack Order",
            "0x1d8 Defend Order",
            "0x1d9 Heal Order",
            "0x1da Head Smash",
            "0x1db Double Hit",
            "0x1dc Roar if Time",
            "0x1dd Special Rend",
            "0x1de Lunar Dance",
            "0x1df Crush Grip",
            "0x1e0 Magma Storm",
            "0x1e1 Dark Void",
            "0x1e2 Seed Flare",
            "0x1e3 Ominous Wind",
            "0x1e4 Shadow Force"});
            this.cbxSelectedAnimFile.Location = new System.Drawing.Point(9, 10);
            this.cbxSelectedAnimFile.Margin = new System.Windows.Forms.Padding(2, 3, 2, 3);
            this.cbxSelectedAnimFile.Name = "cbxSelectedAnimFile";
            this.cbxSelectedAnimFile.Size = new System.Drawing.Size(236, 21);
            this.cbxSelectedAnimFile.TabIndex = 1;
            this.cbxSelectedAnimFile.SelectedIndexChanged += new System.EventHandler(this.cbxSelectedAnimFile_SelectedIndexChanged);
            // 
            // AnimList
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(253, 394);
            this.Controls.Add(this.btnSaveCurrent);
            this.Controls.Add(this.cbxSelectedAnimFile);
            this.Controls.Add(this.listBox1);
            this.Margin = new System.Windows.Forms.Padding(2, 3, 2, 3);
            this.Name = "AnimList";
            this.Text = "AnimList";
            this.Load += new System.EventHandler(this.AnimList_Load);
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.ListBox listBox1;
        private System.Windows.Forms.Button btnSaveCurrent;
        private System.Windows.Forms.ComboBox cbxSelectedAnimFile;
    }
}